# Generated by Django 5.1.1 on 2024-10-18 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 18, 15, 19, 42, 308798), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='hrprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 18, 15, 19, 42, 309798), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 18, 15, 19, 42, 308798), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 18, 15, 19, 42, 309798), null=True, verbose_name='Baholangan vaqt'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 18, 15, 19, 42, 308798), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='users',
            name='joined_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 18, 15, 19, 42, 307798), null=True, verbose_name="Qo'shilgan vaqti"),
        ),
    ]
