# Generated by Django 5.1.1 on 2024-10-09 08:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 9, 13, 8, 0, 566717), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 9, 13, 8, 0, 565717), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 9, 13, 8, 0, 566717), null=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 9, 13, 8, 0, 565717), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='users',
            name='joined_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 9, 13, 8, 0, 564717), null=True, verbose_name="Qo'shilgan vaqti"),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, choices=[('hr', 'HR xodim'), ('user', 'Oddiy foydalanuvchi'), ('teacher', "Ish o'rgatuvchi maxsus xodim"), ('intern', 'Stajor'), ('chief', "Bo'lim boshlig'i"), ('admin', 'Admin')], default='user', max_length=100, null=True, verbose_name='Foydalanuvchi roli'),
        ),
        migrations.CreateModel(
            name='ChiefProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 9, 13, 8, 0, 565717), null=True, verbose_name='Yaratilgan vaqti')),
                ('department', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intern.department', verbose_name="Bo'lim")),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intern.users', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Chief',
                'verbose_name_plural': "Bo'lim boshliqlari",
                'db_table': 'chief_profile',
            },
        ),
    ]
