# Generated by Django 5.1.1 on 2024-10-10 08:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0006_alter_chiefprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intern.chiefprofile', verbose_name="Bo'lim boshlig'i"),
        ),
        migrations.AddField(
            model_name='mark',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intern.hrprofile', verbose_name='Hr xodim'),
        ),
        migrations.AlterField(
            model_name='chiefprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 10, 13, 40, 9, 189617), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='hrprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 10, 13, 40, 9, 190617), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 10, 13, 40, 9, 190617), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 10, 13, 40, 9, 190617), null=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 10, 13, 40, 9, 189617), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='users',
            name='joined_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 10, 13, 40, 9, 188617), null=True, verbose_name="Qo'shilgan vaqti"),
        ),
    ]
