# Generated by Django 5.1.1 on 2024-10-10 09:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0007_mark_chief_mark_hr_alter_chiefprofile_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='chief',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='hr',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='teacher',
        ),
        migrations.AddField(
            model_name='mark',
            name='rated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intern.users', verbose_name='Baholagan shaxs'),
        ),
        migrations.AlterField(
            model_name='chiefprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 10, 14, 6, 19, 549659), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='hrprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 10, 14, 6, 19, 549659), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 10, 14, 6, 19, 549659), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 10, 14, 6, 19, 550659), null=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 10, 14, 6, 19, 548657), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='users',
            name='joined_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 10, 14, 6, 19, 548657), null=True, verbose_name="Qo'shilgan vaqti"),
        ),
    ]
