# Generated by Django 5.1.1 on 2024-10-11 11:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0009_alter_chiefprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 11, 16, 50, 10, 710684), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='hrprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 11, 16, 50, 10, 711684), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 11, 16, 50, 10, 710684), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intern.teacherprofile', verbose_name="Ish o'rgatuchi"),
        ),
        migrations.AlterField(
            model_name='mark',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 11, 16, 50, 10, 711684), null=True, verbose_name='Baholangan vaqt'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 11, 16, 50, 10, 710684), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='users',
            name='joined_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 11, 16, 50, 10, 709683), null=True, verbose_name="Qo'shilgan vaqti"),
        ),
    ]
