# Generated by Django 5.1.1 on 2024-10-18 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0011_internprofile_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=221, null=True, verbose_name='Fayl nomi')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='PDF file')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'pdf_information',
                'verbose_name_plural': 'PDF File',
                'db_table': 'pdf_file',
            },
        ),
        migrations.AlterField(
            model_name='chiefprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 18, 11, 41, 38, 746861), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='hrprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 18, 11, 41, 38, 747862), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 18, 11, 41, 38, 747862), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Aktivligi'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 18, 11, 41, 38, 747862), null=True, verbose_name='Baholangan vaqt'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 18, 11, 41, 38, 746861), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='users',
            name='joined_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 18, 11, 41, 38, 745860), null=True, verbose_name="Qo'shilgan vaqti"),
        ),
    ]
